### ISSUE TITLE
Consider moving to Static class

### ISSUE THREAD

**Issue by tbm0115** [sharksday/assembly#1]
https://github.com/sharksday/assembly/blob/00bf56845ef0bb0321b4bd95882eaa37f35f888c/asm/com/kassmon/assembly/logic/RunTime.java#L173

Due to the nature of what you're doing, it may be more manageable to migrate these command methods into a single Static Class. This will allow you to manage each method in a separate file which will also make it easier to review what commands you have implemented with a quick glance at your project files.

For example, consider the following folder structure:

 - logic
   - commands
     - add.java
     - clk.java
     - div.java
     - *.java (you get the point)

Within each file you should be able to extend the same static class like:

**~/logic/commands/add.java**
``` java
public static class Commands {
  public void add() {
    // Do stuff here
  }
}
```

Structuring this feature into separate files may make it easier to add more complex commands in the future.

**Comment by sharksday** [comment]
Changed how commands are handled
